/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gettoken.h"

bool_t
xdr_token (XDR *xdrs, token *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->token))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->aux))
		 return FALSE;
	return TRUE;
}
